MAnA Laboratories:
  - '(MAnA Laboratories)'
Lunar Laboratory:
  - '(Lunar Laboratory)'
Reincarnation:
  - '(Reincarnation)'
Star Factory:
  - '(Star Factory)'
Arcane Twilight:
  - '(Arcane Twilight)'
Other Modpack:
  - '(Other Modpack)'
